http:
  middlewares:
    strip-todo-db:
      stripPrefix:
        prefixes:
          - "/todo-db"
  routers:
    homarr:
      rule: "Host(`apps.joedodge.dev`) && PathPrefix(`/home`)"
      entryPoints:
        - web
      middlewares:
        - auth
      service: homarr
    todo:
      rule: "Host(`apps.joedodge.dev`) && PathPrefix(`/todo`)"
      entryPoints:
        - web
      service: todo
    todo-db:
      rule: "Host(`apps.joedodge.dev`) && PathPrefix(`/todo-db`)"
      entryPoints:
        - web
      middlewares:
        - auth
        - strip-todo-db
      service: todo-db
  services:
    homarr:
      loadBalancer:
        servers:
          - url: "http://homarr-app:7575"
    todo:
      loadBalancer:
        servers:
          - url: "http://todo-app:3000"
    todo-db:
      loadBalancer:
        servers:
          - url: "http://todo-db-pgweb:8081"
